[workspace]
# https://release-plz.ieni.dev/docs/config#the-release_always-field
# If false, release-plz release will try to release your packages only when you merge the release PR.
# To do this, release-plz checks if the latest commit is associated to a release PR. To determine if a PR is a release-pr
release_always = false

git_release_draft = true
pr_draft = true
pr_labels = ["release"]

# As we cannot regenerate the whole CHANGELOG, we fallback to cliff
# https://github.com/MarcoIeni/release-plz/issues/1009
changelog_config = "cliff.toml"

[[package]]
name = "foundationdb-macros"

[[package]]
name = "foundationdb-sys"
publish_features = ["embedded-fdb-include", "fdb-7_3"]

[[package]]
name = "foundationdb-gen"

[[package]]
name = "foundationdb-tuple"
publish_features = ["uuid", "num-bigint"]

[[package]]
name = "foundationdb"
publish_features = ["embedded-fdb-include", "fdb-7_3", "uuid"]

[[package]]
name = "foundationdb-simulation"
publish_features = ["embedded-fdb-include", "fdb-7_3"]

[[package]]
name = "foundationdb-bench"
publish = false
git_release_enable = false
changelog_update = false

[[package]]
name = "bindingtester"
publish = false
git_release_enable = false
changelog_update = false